services:
  warehouse-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-inventory-api
    ports:
      - "8080:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: warehouse-inventory-swagger
    depends_on:
      - warehouse-api
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
